# Generated by Django 4.2 on 2023-04-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_base_app', '0002_rename_boss_employee_parent'),
    ]

    operations = []
